-- Active: 1678018812392@@127.0.0.1@3306@new_schema
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS rate;
CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  count_like INTEGER,
  count_unlike INTEGER,
  FOREIGN KEY (author_id) REFERENCES user(id)
);
CREATE TABLE rate (
  author_id INTEGER NOT NULL,
  post_id INTEGER NOT NULL,
  liked INTEGER NOT NULL,
  unliked INTEGER NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user(id),
  FOREIGN KEY (post_id) REFERENCES post(id)
);